### ISSUE TITLE
Possible Race Condition on OSX

### ISSUE THREAD

**Issue by smikes** [bterlson/test262-harness#25]
When running a batch of tests on OSX -

```
$ test262-harness test/built-ins/RegExp/*.js
[... many failures...]
FAIL test/built-ins/RegExp/S15.10.3.1_A1_T1.js
     R is /x/i and instance is RegExp(R)
     Exp: no error
     Got: ReferenceError: __patterns is not defined
       at evalmachine.<anonymous>:13:69
       at Socket.<anonymous> (/Users/smikes/src/github/test262-harness/lib/runners/nodehost.js:33:12)
       at Socket.emit (events.js:95:17)
       at Socket.<anonymous> (_stream_readable.js:764:14)
       at Socket.emit (events.js:92:17)
       at emitReadable_ (_stream_readable.js:426:10)
       at emitReadable (_stream_readable.js:422:5)
       at readableAddChunk (_stream_readable.js:165:9)
       at Socket.Readable.push (_stream_readable.js:127:10)
       at Pipe.onread (net.js:528:21)

Ran 407 tests
373 passed
34 failed
Took 2.341 seconds
```

but a single test:

```
$ test262-harness test/built-ins/RegExp/S15.10.3.1_A1_T1.js
Ran 1 tests
1 passed
0 failed
Took 0.116 seconds
```

Most likely cause - a damaged checkout of test262-runner or test262-parser.  I will investigate that.

**Comment by smikes** [comment]
Never got to this. Closing.
