### ISSUE TITLE
`npm test` fails

### ISSUE THREAD

**Issue by smikes** [bterlson/test262-harness#51]
As a fledgling contributor,
I want the unit tests to pass,
so I can add a feature. 

Seriously, though, I don't know where to start attacking this.  Suggestions?

```
> test262-harness@2.0.0 test /Users/smikes/src/github/test262-harness
> tape test/test.js

TAP version 13
# -r node
not ok 1 No stderr is present
  ---
    operator: equal
    expected:
      ''
    actual:
      'module.js:442\n    throw err;\n    ^\n\nError: Cannot find module \'test262-compiler\'\n    at Function.Module._resolveFilename (module.js:440:15)\n    at Function.Module._load (module.js:388:25)\n    at Module.require (module.js:468:17)\n    at require (internal/module.js:20:19)\n    at Object.<anonymous> (/Users/smikes/src/github/test262-harness/bin/run.js:5:17)\n    at Module._compile (module.js:541:32)\n    at Object.Module._extensions..js (module.js:550:10)\n    at Module.load (module.js:458:32)\n    at tryModuleLoad (module.js:417:12)\n    at Function.Module._load (module.js:409:3)\n'
    at: ChildProcess.<anonymous> (/Users/smikes/src/github/test262-harness/test/utils.js:97:9)
  ...
not ok 2 10 tests run
  ---
    operator: equal
    expected: 10
    actual:   0
    at: ChildProcess.<anonymous> (/Users/smikes/src/github/test262-harness/test/utils.js:97:9)
  ...

/Users/smikes/src/github/test262-harness/test/utils.js:13
    throw "Can't find results for " + test.file;
    ^
Can't find results for test/collateral/async.js
npm ERR! Test failed.  See above for more details.
```

**Comment by bterlson** [comment]
Yes sorry, I was in a rush before I left for my 4th of July break to push something. I will be fixing this up soon.

**Comment by bterlson** [comment]
Alright this is fixed :) I added some basic tests that were present from before, though with better (and easier) verification. More tests of different sorts would certainly be welcome, however.

**Comment by smikes** [comment]
no worries.

Confirmed, `npm test` now passes.  Thanks for the quick fix.
